version: "3.4"
services:
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: securityDB
    volumes:
      - './src/main/resources:/docker-entrypoint-initdb.d'
    networks:
      - net
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 2s
  java-app:
    image: security_image:latest
    build: .
    container_name: app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - net
    ports:
      - 8081:8080
networks:
  net:
    external: true