version: "3.4"
services:
  java-app:
    build: .
    container_name: app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - net
    ports:
      - 8081:8080
networks:
  net:
    external: true