version: '3.8'

services:
  media_service:
    build: .
    container_name: mediaStorageApp
    env_file:
      - .env
    networks:
      - net
    ports:
      - 8084:8084

networks:
  net:
    external: true