services:
  master-db:
    image: mysql:latest
    container_name: master-db
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: chat_app_db

    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      timeout: 2s
    networks:
      - net
    volumes:
      - ./db_config/master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-master-data:/var/lib/mysql

  replica-one:
    image: mysql:latest
    container_name: replica-one
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3309:3306"
    networks:
      - net
    depends_on:
      master-db:
          condition: service_healthy
    volumes:
      - mysql-replica-one-data:/var/lib/mysql
      - ./db_config/slave/entrypoint.sh:/entrypoint.sh
    entrypoint: ["chmod +x ./entrypoint.sh && ./entrypoint.sh"]


  replica-two:
    image: mysql:latest
    container_name: replica-two
    command: --server-id=3 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3310:3306"
    networks:
      - net
    depends_on:
      master-db:
        condition: service_healthy
    volumes:
      - mysql-replica-two-data:/var/lib/mysql
      - ./db_config/slave/entrypoint.sh:/entrypoint.sh
    entrypoint: ["chmod +x ./entrypoint.sh && ./entrypoint.sh"]


  app:
    build: .
    container_name: spring-boot-app
    depends_on:
      master-db:
        condition: service_healthy
    networks:
      - net
    ports:
      - "8082:8080"

networks:
  net:
    driver: bridge

volumes:
  mysql-master-data:
  mysql-replica-one-data:
  mysql-replica-two-data:
