name: cs4337-chatforstudents

services:
  zookeeper: #Zookeeper
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: on-failure


  kafka: #First Broker
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    restart: on-failure

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200m

  chat:
      image: cs4337-chatservice
      build:
          context: .
      container_name: chat
      networks:
        - net
      ports:
        - "8080:8080"
      depends_on:
        - kafka
        - zookeeper
      environment:
          SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092,
networks:
  net:
    external: true