name: cs4337-chatforstudents

services:
  chat:
      image: cs4337-chatservice
      container_name: chat
      networks:
        - net
      ports:
        - "8080:8080"
networks:
  net:
    external: true