name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23.0.0+37'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Grant Permissions to gradle
        run:
          cd project;
          chmod +x gradle;

      - name: Build with Gradle Wrapper
        run: cd project; ./gradle build -x test;

  test:
    name: GradleTest
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23.0.0+37'
          distribution: 'temurin'

      - name: Grant Permissions to gradle
        run:
          cd project;
          chmod +x gradle;

      - name: Test
        run:
          cd project;
          ./gradle test --tests "*";
